// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChocoShop.Data.Migrations
{
    [DbContext(typeof(ChocoShopContext))]
    [Migration("20221204133622_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ChocoShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Snickers is a chocolate bar made by the American company Mars, Incorporated, consisting of nougat topped with caramel and peanuts that is encased in milk chocolate.",
                            ImageName = "Snickers.jpeg",
                            Name = "Snickers",
                            Price = 73.000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Milky Way is a brand of chocolate-covered confectionery bar manufactured and marketed by Mars, Incorporated. The Milky Way bar is made of nougat, topped with caramel and covered with milk chocolate.",
                            ImageName = "Milkyway.jpg",
                            Name = "Milky Way",
                            Price = 30.000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bounty is a coconut-filled, chocolate-enrobed candy bar manufactured by Mars, Incorporated, introduced in 1951 in the United Kingdom and Canada. Bounty has a coconut filling, enrobed with milk chocolate (in a blue wrapper) or dark chocolate (in a red wrapper) and is usually sold as two small bars wrapped in one package.",
                            ImageName = "Bounty.jpg",
                            Name = "Bounty",
                            Price = 32.000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mars, commonly known as Mars bar, is the name of two varieties of chocolate bar produced by Mars, Incorporated. A delicious fusion of chocolate, caramel and nougat.",
                            ImageName = "Mars.jpg",
                            Name = "Mars",
                            Price = 13.000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Twix is a caramel shortbread chocolate bar made by Mars, Inc., consisting of a biscuit applied with other confectionery toppings and coatings (most frequently caramel and milk chocolate). Twix are packaged with one, two or four bars in a wrapper.",
                            ImageName = "Twix.jpg",
                            Name = "Twix",
                            Price = 17.000m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kinder Maxi is a milk chocolate bar with a soft tasty milky filling that gives you the pleasure and taste of when you were a child.",
                            ImageName = "Kindermaxi.jpg",
                            Name = "Kinder Maxi",
                            Price = 13.000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
